### Listar todas as categorias
GET http://localhost:5273/categoria/listar

### Cadastrar uma categoria
POST http://localhost:5273/categoria/cadastrar
Content-Type: application/json

{
    "nome": "Pessoal"
}